### ISSUE TITLE
[Suggestion] Stop from switching GPU

### ISSUE THREAD

**Issue by SgtSalmon** [simonheys/wordclock#251]
This particular screensaver utilizes the "LegacyScreenSaver" process, which defaults to using the discrete gpu. As this is just words, the iGPU should be sufficient. This way, it won't be a power drain.

**Comment by Vaporjawn** [comment]
I agree with this. Ever since I updated to `MacOS 14 Sonoma`, I've experienced significant performance issues using this screensaver. It usually makes my MacBook go from cold to warm while running no other apps.

**Comment by simonheys** [comment]
Thank you for taking the time to report this - will continue in #256
